version: '3.8'
services:
    aaa_ds_course:
        image: jonfun/aaa_iris_pipeline:0.0.1
        ports:
            - "8088:8088"
        volumes:
            - ./:/app
        command: /bin/bash -c "cd / && jupyter notebook --ip=0.0.0.0 --no-browser  --allow-root  --port=8088  --NotebookApp.token=crmteam01!"
        restart: unless-stopped